[package]
name = "box-rope"
version = "0.1.0"
authors = ["Sam Smith <sam.henning.smith@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath="0.17.0"
image = "0.23.3"
rayon = "1.3.1"

